### ISSUE TITLE
Checklist for 2017-02-11 TCW RelEng actions

### ISSUE THREAD

**Issue by hwine** [hwine/innodb-cutover#15]
Before start of TCW:
 - [x] update checkout of [build-ansible](https://github.com/mozilla-releng/build-ansible)
 - [x] update checkout of [puppet](https://hg.mozilla.org/build/puppet)
 - [x] establish VPN access
 - [x] log into [treestatus](https://treestatus.mozilla.org)

Close Trees via [treestatus](https://treestatus.mozilla.org):
 - [x] Close "autoland" first, remembering history, cite bug 1324148
 - [x] Close all other trees, remembering history, cite bug 1324148
 - [x] Notify #moc that trees are closed.

Immediately continue with shutting down apps connected to BB database:
 - [x] stop all BB masters using scripts
 - [x] stop all BB schedulers using scripts
 - [x] Ask #moc to `graceful-stop` apache on releng web cluster hosts (see [bug 1338269](https://bugzilla.mozilla.org/show_bug.cgi?id=1338269))
 - [x] stop all self serve agents following [ansible script instructions](https://github.com/mozilla-releng/build-ansible#readme)
 - [x] Stop BBB agents following [ansible script instructions](https://github.com/mozilla-releng/build-ansible#readme)
 - [x] Ask #moc to verify no connections to `buildbot-rw-vip.db.scl3.mozilla.com` at ZLB
 - [x] Tell #moc that db work can begin

Wait until #moc says all db work completed:
 - [x] Start self serve agents following [ansible script instructions](https://github.com/mozilla-releng/build-ansible#readme)
 - [x] Start BBB agents following [ansible script instructions](https://github.com/mozilla-releng/build-ansible#readme)
 - [x] Ask #moc to restart apache on releng web cluster hosts (see [bug 1338269](https://bugzilla.mozilla.org/show_bug.cgi?id=1338269))
 - [x] Start BB masters using scripts
 - [x] Start BB schedulers using scripts
 - [x] Monitor system and take care of any issues
 - [x] If a sheriff is around, ask them to vet the state of the system
 - [x] Let #moc know that we're ready to reopen trees

Wait until #moc says trees are ready to be reopened:
 - [x] Open all trees except autoland via [treestatus](https://treestatus.mozilla.org)
 - [x] If a sheriff is around, ask them to vet load on system
 - [x] tell #moc that trees are open
 - [x] wait 10 minutes and reopen autoland via [treestatus](https://treestatus.mozilla.org) (to allow normal load to schedule first)
